In [6]:
import numpy as np

numbers = np.array([10, 20, 30, 40, 50])

print(numbers)

[10 20 30 40 50]


In [11]:
# matrix = np.array([
#     [1,2,3],
#     [4,5,6]
# ])
# print(matrix)
# print(matrix.shape)

matrix =np.array([
    [10,20,30],
    [40,50,60]
])
print(matrix)
print(matrix.shape)


[[10 20 30]
 [40 50 60]]
(2, 3)


In [20]:
# print(np.zeros(5))
# print(np.ones(5))
# print(np.arange(1,10))
print(np.zeros(5))
print(np.ones(7))
print(np.arange(1,50))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1.]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]


In [27]:
# number = np.array([10,20.30,40,50])
# print(numbers[0])
# print(numbers[2])
# print(numbers[3])
# print(numbers[4])
# print(numbers[-3])
number = np.array([10,20,30,40,50,60])
print(number[0])
print(number[1])
print(number[2])
print(number[3])

10
20
30
40


In [39]:
# matrix = np.array([
#     [10,20,30],
#     [40,50,60]
# ])
# print(matrix[0,0])
# print(matrix[1,2])
matrix = np.array([
    [10,20,30],
    [40,50,60]
])
print(matrix[0,0])
print(matrix[1,2])

10
30


In [56]:
# numbers = np.array([10,20,30,40,50])
# print(numbers[0:3])
# print(numbers[0:4])
# print(numbers[1:4])
# print(numbers[:3])
numbers = np.array([10,20,30,40,50])

print(numbers[0:3])
print(numbers[1:4])
print(numbers[1:3])






[10 20 30]
[20 30 40]
[20 30]


In [62]:
# # random numbers 
# numbers = np.random.randint(1,100,10)
# print(numbers)
number = np.random.randint(1,200,20)
print(numbers)

[75 80 98 84 96 67 53 42 62 56]


In [65]:
# # decimal numbers
# numbers = np.random.rand(5)
# print(numbers)
numbers = np.random.rand(5)
print(numbers)

[0.34761064 0.23861469 0.2198461  0.71863439 0.21977575]


In [66]:
np.random.seed(42)
print(np.random.randint(1,200,5))

[103 180  93  15 107]


In [73]:
# bonus caculation
marks = np.array([50,60,70,80,90])
print("Total:",marks.sum())
print("Average:",marks.mean())
print("sabse kam:",marks.min())
print("sabse ziada",marks.max())
print(marks + 5)
print(marks*2)

Total: 350
Average: 70.0
sabse kam: 50
sabse ziada 90
[55 65 75 85 95]
[100 120 140 160 180]


In [78]:
marks = np.array([45,78,90,33,67,88,55,72,95,60])
print("Total:",marks.sum())
print("Average:",marks.mean())
print(marks[0:5])
print(marks+5)

Total: 683
Average: 68.3
[45 78 90 33 67]
[ 50  83  95  38  72  93  60  77 100  65]
