In [5]:
import numpy as np
import pandas as pd 

numbers = np.array([10, 20, 30, 40, 50])

print(numbers)


[10 20 30 40 50]
<class 'pandas.DataFrame'>


In [11]:
# matrix = np.array([
#     [1,2,3],
#     [4,5,6]
# ])
# print(matrix)
# print(matrix.shape)

matrix =np.array([
    [10,20,30],
    [40,50,60]
])
print(matrix)
print(matrix.shape)


[[10 20 30]
 [40 50 60]]
(2, 3)


In [20]:
# print(np.zeros(5))
# print(np.ones(5))
# print(np.arange(1,10))
print(np.zeros(5))
print(np.ones(7))
print(np.arange(1,50))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1.]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]


In [27]:
# number = np.array([10,20.30,40,50])
# print(numbers[0])
# print(numbers[2])
# print(numbers[3])
# print(numbers[4])
# print(numbers[-3])
number = np.array([10,20,30,40,50,60])
print(number[0])
print(number[1])
print(number[2])
print(number[3])

10
20
30
40


In [39]:
# matrix = np.array([
#     [10,20,30],
#     [40,50,60]
# ])
# print(matrix[0,0])
# print(matrix[1,2])
matrix = np.array([
    [10,20,30],
    [40,50,60]
])
print(matrix[0,0])
print(matrix[1,2])

10
30


In [56]:
# numbers = np.array([10,20,30,40,50])
# print(numbers[0:3])
# print(numbers[0:4])
# print(numbers[1:4])
# print(numbers[:3])
numbers = np.array([10,20,30,40,50])

print(numbers[0:3])
print(numbers[1:4])
print(numbers[1:3])






[10 20 30]
[20 30 40]
[20 30]


In [62]:
# # random numbers 
# numbers = np.random.randint(1,100,10)
# print(numbers)
number = np.random.randint(1,200,20)
print(numbers)

[75 80 98 84 96 67 53 42 62 56]


In [65]:
# # decimal numbers
# numbers = np.random.rand(5)
# print(numbers)
numbers = np.random.rand(5)
print(numbers)

[0.34761064 0.23861469 0.2198461  0.71863439 0.21977575]


In [66]:
np.random.seed(42)
print(np.random.randint(1,200,5))

[103 180  93  15 107]


In [73]:
# bonus caculation
marks = np.array([50,60,70,80,90])
print("Total:",marks.sum())
print("Average:",marks.mean())
print("sabse kam:",marks.min())
print("sabse ziada",marks.max())
print(marks + 5)
print(marks*2)

Total: 350
Average: 70.0
sabse kam: 50
sabse ziada 90
[55 65 75 85 95]
[100 120 140 160 180]


In [78]:
marks = np.array([45,78,90,33,67,88,55,72,95,60])
print("Total:",marks.sum())
print("Average:",marks.mean())
print(marks[0:5])
print(marks+5)

Total: 683
Average: 68.3
[45 78 90 33 67]
[ 50  83  95  38  72  93  60  77 100  65]


In [3]:
marks = pd.Series([80,75,90,60])
print(marks)

0    80
1    75
2    90
3    60
dtype: int64


In [11]:
marks =pd.Series([80,75,90], index =["Ali","Ahmed","Amjad"])
print(marks)


Ali      80
Ahmed    75
Amjad    90
dtype: int64


In [20]:
# deta ={
#     "name":["Amjad","Ali","Mazari"],
#     "Age":[20,25,29],
#     "Marks":[80,75,90]
# }
# df = pd.DataFrame(data)
# print(df)

In [38]:
# data ={
#     "names":["Akbar","Amjad","Suhail"],
#     "Ages": [40,21,20],
#     "Marks":[90,80,75]

# }
# df = pd.DataFrame = (data)
# print(df)

In [13]:
df =pd.DataFrame({
    "Date":["2026-01-05","2026-02-15","2026-03-20"],
    "Sale":[1000,1500,2000]
})
df["Date"]=pd.to_datetime(df["Date"])
print(df["Date"].dt.year)
print(df["Date"].dt.month)
print(df["Date"].dt.day)

0    2026
1    2026
2    2026
Name: Date, dtype: int32
0    1
1    2
2    3
Name: Date, dtype: int32
0     5
1    15
2    20
Name: Date, dtype: int32


In [9]:
# # topic 53
# # csv excel json 

# df =pd.DataFrame({
#     "Name":["Ali","Ahmed"],
#     "Marks":[80,90]
# })
# # save
# df.to_csv("students.csv",index=False)
# df.to_json("students.json")
# df.to_excel("students.xlsx",index=False)

# # read

# df1 = pd.read_csv("students.csv")
# df2 = pd.read_json("students.json")
# df3 = pd.read_excel("students.xlsx")
# print(df1)
# print(df2)
# print(df3)

In [18]:
df = pd.DataFrame({
    "Name":["Amjad", "Suhail"],
    "Marks":[90,80]
})
# save
df.to_csv("students.csv",index = False)
df.to_json("students.json")
df.to_excel("students.xlsx",index = False)

# read
df1 = pd.read_csv("students.csv")
df2 = pd.read_json("students.json")
df3 = pd.read_excel("students.xlsx")
print(df1)

     Name  Marks
0   Amjad     90
1  Suhail     80


In [40]:
#  Data types & conversion (Topic 58)

df = pd.DataFrame({
    "Age":["20","22","21"],
    "Marks":["80","75","90"]
})
# object text

print(df.dtypes) 

df["Age"] = df["Age"].astype(int)
df["Marks"] = df["Marks"].astype(float)
print(df.dtypes)

Age      str
Marks    str
dtype: object
Age        int64
Marks    float64
dtype: object


In [48]:
# 1️⃣4️⃣ Missing data (Topic 59)
df = pd.DataFrame({
    "Name": ["Ali", "Ahmed", "Amjad"],
    "Age": [20, np.nan, 22],
    "Marks": [80, 75, np.nan]
})

df["Age"] = df["Age"].fillna(0)              # 0 se bharo
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())  # average se bharo

df2 = df.dropna()            # missing wali row hata do
print(df.isnull())          # True/False
print(df.isnull().sum()) 


    Name    Age  Marks
0  False  False  False
1  False  False  False
2  False  False  False
Name     0
Age      0
Marks    0
dtype: int64


In [49]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Ali", "Ahmed", "Amjad"],
    "Marks": [80, 95, 70]
})

print(df.sort_values("Marks"))                    # kam se zyada
print(df.sort_values("Marks", ascending=False))   # zyada se kam

df["Rank"] = df["Marks"].rank(ascending=False)
print(df)

    Name  Marks
2  Amjad     70
0    Ali     80
1  Ahmed     95
    Name  Marks
1  Ahmed     95
0    Ali     80
2  Amjad     70
    Name  Marks  Rank
0    Ali     80   2.0
1  Ahmed     95   1.0
2  Amjad     70   3.0


In [50]:
import pandas as pd

students = pd.DataFrame({
    "ID": [1, 2, 3],
    "Name": ["Ali", "Ahmed", "Amjad"]
})

marks = pd.DataFrame({
    "ID": [1, 2, 4],
    "Marks": [80, 90, 75]
})

print(pd.merge(students, marks, on="ID"))                 # sirf matching (inner)
print(pd.merge(students, marks, on="ID", how="left"))     # saare students
print(pd.merge(students, marks, on="ID", how="outer"))    # dono ka sab

   ID   Name  Marks
0   1    Ali     80
1   2  Ahmed     90
   ID   Name  Marks
0   1    Ali   80.0
1   2  Ahmed   90.0
2   3  Amjad    NaN
   ID   Name  Marks
0   1    Ali   80.0
1   2  Ahmed   90.0
2   3  Amjad    NaN
3   4    NaN   75.0


In [51]:
# 1️⃣8️⃣ apply, map, pipe (Topic 63)
import pandas as pd

df = pd.DataFrame({
    "Name": ["Ali", "Ahmed", "Amjad"],
    "Marks": [50, 70, 90],
    "Gender": ["M", "F", "M"]
})

# apply -> apna function lagao
def add_bonus(m):
    return m + 5

df["New_Marks"] = df["Marks"].apply(add_bonus)

# lambda (chhota function)
df["Grade"] = df["Marks"].apply(lambda x: "Pass" if x >= 60 else "Fail")

# map -> value badalna (dictionary se)
df["Gender"] = df["Gender"].map({"M": "Male", "F": "Female"})

print(df)

    Name  Marks  Gender  New_Marks Grade
0    Ali     50    Male         55  Fail
1  Ahmed     70  Female         75  Pass
2  Amjad     90    Male         95  Pass
